#!/usr/bin/env python

import sys
import os

import mmserp.hdf5browser as hu

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Error: call as ./{} <filename>".format(os.path.basename(__file__)))
    else:
        hu.show_menu(sys.argv[1])

